name: Discloud Deploy Action
description: Deploy your Discloud app

branding:
  icon: upload-cloud
  color: green

inputs:
  token:
    required: true
    description: "Token to use Discloud api"

  app_id:
    description: "App ID (default:`discloud.config`#`ID`)"

  env:
    description: "Environment variables to add to zip"

  env_file:
    description: "Env file name"

  glob:
    default: "**"
    description: "Specify the glob pattern to filter files to be uploaded"

  team:
    description: "Specify if the app is a `team` app. Ignore if the app is yours"
    default: "false"

runs:
  using: node20
  main: dist/index.js
