name: Release new action version

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Installing dependencies
        run: yarn

      - name: Testing
        run: npm run test

  update_tag:
    name: Update the major tag to include the ${{ github.event.release.tag_name }} changes
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Update the ${{ github.event.release.tag_name }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
