name: Release new action version

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  update_tag:
    name: Update the major tag to include the ${{ github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    steps:
      - name: Update the ${{ github.event.release.tag_name }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
