name: Release new action version

on:
  release:
    types: [released]

env:
  TAG_NAME: ${{ github.event.release.tag_name }}
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Installing dependencies
        run: yarn
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run package

  update_tag:
    name: Update the major tag to include the ${{ github.event.release.tag_name }} changes
    runs-on: ubuntu-latest
    steps:
      - name: Update the ${{ env.TAG_NAME }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ env.TAG_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
