name: Release new action version

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update the ${{ github.event.release.tag_name }} tag
        uses: actions/publish-action@v0.3.0
        with:
          source-tag: ${{ github.event.release.tag_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
